name 'WebServices'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures WebServices'
long_description 'Installs/Configures WebServices'
version '0.1.0'
